### PR TITLE
Added a link

### PR DESCRIPTION
**Pull request by joker314**
I can't test it, but there is a chance of it being underlined (possibly a good thing?)

### CODE REVIEW

**Comment by mundofinky** [comment]
Preview: https://scratchmessages.blogspot.com.ar/p/note-if-messages-number-is-higher-than.html

**Comment by mundofinky** [comment]
Do you like it?

**Comment by joker314** [comment]
Yes, I like it

**Comment by mundofinky** [comment]
Updated on website

**Pull request merged**
